# Generated by Django 3.1.3 on 2020-11-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('automat', 'Automat')], default='automat', max_length=10)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
